# This file is automatically generated by organize_pdfs.sh
# the format is [category]="subcategory1 subcategory2 ..."
declare -A categories=(
    [Programming]="Python Java C"
    [AI]="Machine_Learning Neural_Networks"
    [Math]="Linear_Algebra Calculus"
    [Database]="SQL NoSQL"
    [Security]="Cryptography Networks_Security"
    )
